config/routes.rb
Spree::Core::Engine.add_routes do
  get '/:taxon/inspirez-vous/:slug', to: 'lookbooks#show', as: :show_lookbook
  # get '/:taxon/inspirez-vous/:slug/:kit', to: 'kits#show', as: :show_kit
  get '/kits/:slug', :to => 'kits#show_single_kit', :as => :show_single_kit
  # route globbing for pretty nested taxon and product paths
  get '/*taxon/inspirez-vous/:slug/:kit', :to => 'kits#show', :as => :show_kit


  namespace :admin do
    get '/kits/add_product/', to: 'kits#add_product'
    get '/lookbooks/kits/add_product/', to: 'lookbooks/kits#add_product'
    get '/lookbooks/add_kit/', to: 'lookbooks#add_kit'



    concern :positionable do
      collection do
        post :update_positions
      end
    end

    resources :kits    do
      collection do
        get :search
      end
    end

    resources :kits, concerns: :positionable, controller: 'kits' do
      #admin_kit_update_product_position_path
      post "update_product_position", to: "kits#update_product_positions", as: :update_kits_product_position
    end
    resources :lookbooks, concerns: :positionable, path: "LB" do
      resources :kits, concerns: :positionable, controller: "lookbooks/kits" do
        # admin_lookbook_kit_update_product_position_path
        post "update_product_position", to: "lookbooks/kits#update_product_positions", as: :update_product_position
      end
      post "edit", to: "lookbooks#edit order"
    end



  end
end

app/models/spree/kit.rb
module Spree
  class Kit < Spree::Base
    extend FriendlyId

    has_many :spree_kits_products, -> { order(:position) }, class_name: "Spree::KitProduct"
    has_many :spree_kits_lookbooks, class_name: "Spree::KitLookbook"
    has_many :spree_kits_taxons,  class_name: "Spree::KitTaxon"


    has_many :products, :through => 'spree_kits_products', class_name: "Spree::Product"
    has_many :lookbooks, :through => 'spree_kits_lookbooks', class_name: "Spree::Lookbook"
    has_many :taxons, :through => 'spree_kits_taxons', class_name: "Spree::Taxon"

    translates :name, :image, :slug, presence: true
    accepts_nested_attributes_for :translations, :spree_kits_products, :taxons,  allow_destroy: true


    has_many :images
    friendly_id :slug_candidates, use: :globalize

    def slug_candidates
      [[:name]]
    end
    def image_for product, format = :large
      skp = spree_kits_products.find_by(product: product)
      if skp && skp.image?
         skp.image.url(format)
      else
        if product.images.empty?
          unless product.variants.joins(:images).any?
            return "noimage/product.png"
          end
          return product.variants.joins(:images).first.images.first.attachment.url(format)
        else
          image = product.images.first
          image.attachment.url(format)
        end
      end
    end

    #paperclip is annoying so quick hack/fix
    def as_json options

      {
          name: name,
          id: id
      }

    end



    class Translation
      belongs_to :spree_kit
      has_attached_file :image,

                        styles: { mini: '32x32>', normal: '128x128>', large: '1500x760' },
                        default_style: :large
      validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

    end

  end
end

app/models/spree/lookbook.rb
module Spree
  class Lookbook < Spree::Base
    extend FriendlyId

    has_many :images


    has_many :spree_kits_lookbooks, -> { order(:position) }, class_name: "Spree::KitLookbook"

    has_many :kits, :through => 'spree_kits_lookbooks', class_name: "Spree::Kit"




    belongs_to :spree_taxon,  class_name: "Spree::Taxon"
    translates :name, :image, :slug, presence: true

    accepts_nested_attributes_for :translations, :spree_kits_lookbooks, allow_destroy: true

    friendly_id :slug_candidates, use: [:globalize, :history]

    def slug_candidates
      [[:name],[:name, :id]]
    end

    class Translation
      belongs_to :spree_lookbook
      has_attached_file :image,

                        styles: { mini: '32x32>', normal: '128x128>', large: '1500x760' },
                        default_style: :large
      validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]


    end




  end
end

app/controllers/spree/admin/lookbooks/kits_controller.rb
module Spree
  module Admin
    module Lookbooks
      class KitsController < ResourceController

        before_action :load_lookbook, except: :add_product
        before_action :setup_taxons_correctly, only: :update
        respond_to :js, only: [:add_product]

        def index
          @kits = Spree::Kit.all
        end

        #retourne un js qui pop une ligne dans un tableau
        def add_product
          @product = Spree::Product.find(params[:product_id])

          puts ("WTTTTFFFFFFFFFFF")
          puts @product.inspect
          respond_to do |format|
            format.js {}
          end


        end

        def load_lookbook
          @lookbook = Lookbook.friendly.find(params[:lookbook_id])
        end


        def create
          super
          @lookbooks_kit.lookbooks << @lookbook
          @lookbooks_kit.save
        end

        def update_positions
          ActiveRecord::Base.transaction do
            params[:positions].each_with_index do |id, index|
              puts id
              puts index
              @lookbook.spree_kit_lookbook.find_by(kit_id: id).update(position: index+1)
            end
          end

          respond_to do |format|
            format.js { render text: 'Ok' }
          end
        end

        def update_product_positions
          @kit = Spree::Kit.friendly.find(params[:kit_id])
          ActiveRecord::Base.transaction do
            params[:positions].each_with_index do |id, index|
              puts id
              puts index
              @kit.spree_kits_products.find_by(spree_product_id: id).update(position: index+1)
            end
          end

          respond_to do |format|
            format.js { render text: 'Ok' }
          end
        end

        def find_resource

          Spree::Kit.friendly.find(params[:id])
        end

        private
        def model_class
          Spree::Kit
        end

        def setup_taxons_correctly
          if params[:kit][:taxon_ids].present?
            params[:kit][:taxon_ids] = params[:kit][:taxon_ids].split(',')
          end
        end

        def permitted_resource_params
          params["kit"].present? ? params.require("kit").permit! : ActionController::Parameters.new
        end

        def location_after_save
          edit_admin_lookbook_path(@lookbook)
        end

        def find_resource

          if params[:id]
            Spree::Kit.friendly.find(params[:id])
          else
            Spree::Kit.friendly.find(params[:kit_id])

          end
        end

      end
    end
  end
end

app/controllers/spree/admin/lookbooks_controller.rb
module Spree
  module Admin
    class LookbooksController < ResourceController

      before_action :load_data, except: [:index, :new]


      def index
        @lookbooks = Spree::Lookbook.all
      end

      def load_data
        if params[:id]
         @lookbook = Spree::Lookbook.friendly.find(params[:id])
        else
          @lookbook = Spree::Lookbook.new unless @lookbook
        end
      end


      def new_kit
        @kit = Kit.new
         render( template: "spree/admin/lookbooks/kits/new", locals: {resource: @kit})
      end

      def add_kit
        @kit = Spree::Kit.find(params[:kit_id])

        respond_to do |format|
          format.js {}
        end


      end



      private
      def lookbook_params
        params.require(:lookbook).permit(:name, :taxon_id)
      end

      def find_resource
        if parent_data.present?
          parent.send(controller_name).friendly.find(params[:id])
        else
          model_class.friendly.find(params[:id])
        end
      end



    end
  end
end

app/controllers/spree/lookbooks_controller.rb
module Spree
  class LookbooksController < Spree::StoreController
    respond_to :js, :html

    def show
      if params[:slug]
        @lookbook = Spree::Lookbook.friendly.find(params[:slug])
      else
        @lookbook = Spree::Lookbook.joins(:kits).order(created_at: :desc).first
      end
        @kit = @lookbook.kits.first
      if request.path != show_lookbook_path(@taxon, @lookbook)
         redirect_to show_lookbook_path(@taxon, @lookbook), :status => :moved_permanently and return
      end
    end

    private
    def find_taxon
      @taxon = Spree::Taxon.friendly.find(params[:taxon])
    end
  end
end

app/views/spree/admin/lookbooks/_form.html.erb
<% content_for :page_actions do %>
    <%= button_link_to Spree.t(:back_to_resource_list, resource: plural_resource_name(Spree::Lookbook)), spree.admin_lookbooks_path, icon: 'arrow-left', class: 'btn-primary' %>
<% end %>

<%puts resource.inspect %>
<%= form_for [:admin, resource], multipart: true do |f| %>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :name, Spree::Lookbook.human_attribute_name(:name) %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
      </div>
      <div class="col-md-6">
        <%= f.field_container :taxons, class: ['form-group'] do %>
            <%= f.label :taxon_id, Spree.t(:taxon) %>

            <% if can? :modify, Spree::Classification %>
                <%= f.hidden_field :spree_taxon_id, value: @lookbook.spree_taxon_id, class: "taxon_picker" %>
            <% elsif @lookbook.taxon.any? %>
                <ul class="text_list">
                  <%= "<li>#{@lookbook.taxon.name}</li>" %>
                </ul>
            <% else %>
                <div class="alert alert-info"><%= Spree.t(:no_resource_found, resource: :taxons) %></div>
            <% end %>

        <% end %>
      </div>

      <div class="col-md-12">
        <%= f.field_container :kit_id, class: ['form-group'] do %>
            <%= f.label :kit_id, Spree.t('choose_kit') %> <span class="required">*</span>
            <%= hidden_field_tag :kit_id, "", class: "kit_picker", data: {
                                                    url: "/admin/lookbooks/add_kit",
                                                    remote: true }
            %>
            <%= error_message_on :kit, :product_ids, :class => 'error-message' %>
        <% end %>
      </div>
    </div>

    <%= render "spree/admin/shared/#{resource.new_record? ? 'new' : 'edit'}_resource_links" %>
    <% if f.object.persisted? %>
        <div class ='translationDiv'>
          <%= link_to_with_icon 'translate', nil, admin_translations_path('lookbook', f.object.id), title: Spree.t(:'i18n.translations'), class: 'btn btn-sm btn-primary' %>
        </div>


        <table class="table sortable" id="listing-kits" data-sortable-link="<%= update_positions_admin_lookbook_kits_path(@lookbook) %>">
          <thead>
          <tr data-hook="option_header">
            <th class="no-border"></th>
            <th><%= Spree.t(:kit) %></th>
            <th class="actions"></th>
          </tr>
          </thead>
          <tbody>
          <% @lookbook.spree_kits_lookbooks.each do |skl| %>
              <%= render "kit_line", {kit: skl.kit, skl: skl} %>
          <% end %>
          </tbody>
        </table>
    <% end %>

<% end %>

app/views/spree/admin/lookbooks/_kit_line.html.erb
<tr id="<%= spree_dom_id kit %>">
  <% line_id = (defined? skl )? skl.id : rand(500..500000) %>
  <% if defined? skl %>
      <%= hidden_field_tag "lookbook[spree_kits_lookbooks_attributes][#{line_id}][id]", skl.id %>

  <% end %>
  <%= hidden_field_tag "lookbook[spree_kits_lookbooks_attributes][#{line_id}][kit_id]", kit.id %>
  <%= hidden_field_tag "lookbook[spree_kits_lookbooks_attributes][#{line_id}][_destroy]", "false", data:{hook: "deleter"} %>

  <td class="handle move-handle"><span class="icon icon-move handle"></span></td>
  <td class="presentation"><%= kit.name %></td>
  <td class="actions actions-2 text-right">
    <% if @lookbook && !(defined? no_edit) %>
      <%= link_to_edit(kit.id, class: 'admin_edit_option_type', no_text: true, url: edit_admin_lookbook_kit_path(@lookbook, kit)) %>
        <%= link_to_with_icon 'delete', "", "#remove_line", class: "btn btn-danger btn-sm deete-resource" %>
    <% end %>
  </td>
</tr>

app/views/spree/admin/lookbooks/add_kit.js.erb
$("#listing-kits").append("<%= j (render "kit_line", {kit: @kit, no_edit: true}) %>");

$("#kit_id").select2("val", "");

app/views/spree/admin/lookbooks/edit.html.erb
<% content_for :page_title do %>
    <%= Spree.t(:editing_resource, resource: plural_resource_name(Spree::Lookbook)) %>
<% end %>

<% content_for :page_actions do %>
    <%= button_link_to Spree.t(:add_kit, scope: :kit), spree.new_admin_lookbook_kit_path(@lookbook), icon: 'add', class: 'btn-success', id: 'new_lookbook_link' %>
<% end %>

<%= render 'form', resource: @lookbook %>

<% SpreeI18n::Config.available_locales.each do |locale| %>
    <% if @lookbook.translation_for(locale).image? %>
      <img src ="<%= @lookbook.image(locale).url(:large) %>"/>
    <% end %>
<% end %>

app/views/spree/admin/lookbooks/index.html.erb
<% content_for :page_title do %>
    <%= Spree.t(:lookbooks) %>
<% end %>

<% content_for :page_actions do %>
    <span id="new_ot_link">
      <%= button_link_to Spree.t(:new_lookbook), spree.new_admin_lookbook_path, { :icon => 'SS', :id => 'admin_new_lookbook', :class => 'btn-success' } %>
    </span>
<% end %>


<% if @lookbooks.any? %>

    <table class="table sortable" id="listing-store-locations data-hook">
      <thead>
      <tr data-hook="option_header">
        <th><%= Spree.t(:lookbook) %></th>
        <th class="actions"></th>
      </tr>
      </thead>
      <tbody>
      <% @lookbooks.each do |lookbook| %>
          <tr id="<%= spree_dom_id lookbook %>">
            <td class="presentation"><%= lookbook.name %></td>
            <td class="actions actions-2 text-right">
              <%= link_to_edit(lookbook.id, class: 'admin_edit_option_type', no_text: true) %>
              <%= link_to_delete(lookbook, no_text: true) %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>

<% else %>
    <div class="alert alert-info no-objects-found">
      <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::SizingChart)) %>,
      <%= link_to Spree.t(:add_one), new_admin_lookbook_path %>!
    </div>
<% end %>

app/views/spree/admin/lookbooks/new.html.erb
<% content_for :page_title do %>
    <%= Spree.t(:new_lookbook) %>
<% end %>

<%= render 'form', resource: @lookbook %>