config/routes.rb
Spree::Core::Engine.add_routes do
  get '/:taxon/inspirez-vous/:slug', to: 'lookbooks#show', as: :show_lookbook
  # get '/:taxon/inspirez-vous/:slug/:kit', to: 'kits#show', as: :show_kit
  get '/kits/:slug', :to => 'kits#show_single_kit', :as => :show_single_kit
  # route globbing for pretty nested taxon and product paths
  get '/*taxon/inspirez-vous/:slug/:kit', :to => 'kits#show', :as => :show_kit


  namespace :admin do
    get '/kits/add_product/', to: 'kits#add_product'
    get '/lookbooks/kits/add_product/', to: 'lookbooks/kits#add_product'
    get '/lookbooks/add_kit/', to: 'lookbooks#add_kit'



    concern :positionable do
      collection do
        post :update_positions
      end
    end

    resources :kits    do
      collection do
        get :search
      end
    end

    resources :kits, concerns: :positionable, controller: 'kits' do
      #admin_kit_update_product_position_path
      post "update_product_position", to: "kits#update_product_positions", as: :update_kits_product_position
    end
    resources :lookbooks, concerns: :positionable, path: "LB" do
      resources :kits, concerns: :positionable, controller: "lookbooks/kits" do
        # admin_lookbook_kit_update_product_position_path
        post "update_product_position", to: "lookbooks/kits#update_product_positions", as: :update_product_position
      end
      post "edit", to: "lookbooks#edit order"
    end



  end
end

app/views/spree/admin/translations/kit.html.erb
<% content_for :page_actions do %>
    <%= button_link_to Spree.t(:back_to_resource_list, resource: Spree::Kit.model_name.human), edit_admin_kit_path(@kit), class: 'btn-primary', icon: 'arrow-left' %>
<% end %>
<% @resource = @kit %>

<%= render 'settings' %>

<div class="row translations">
  <div class="col-md-4">
    <div class="panel panel-default fields">
      <div class="panel-heading"><%= Spree.t(:'i18n.fields') %></div>
      <div class="list-group" id="attr_list">
        <a class="list-group-item active" data-attr="name" href="#"><%= Spree.t("name") %></a>
        <a class="list-group-item " data-attr="image" href="#"><%= Spree.t("image") %></a>
        <a class="list-group-item" data-attr="slug" href="#"><%= Spree.t("slug") %></a>
      </div>
    </div>
  </div>
  <div class="col-md-8">
    <%= form_for [:admin, @resource], :html => {:multipart => true}  do |f| %>
        <div id="attr_fields">
          <% SpreeI18n::Config.available_locales.each do |locale| %>
              <%= f.globalize_fields_for locale.to_sym do |g| %>
                  <% @resource.class.translated_attribute_names.each_with_index do |attr, i| %>
                      <% next unless @resource.translation.class.columns_hash[attr.to_s] %>
                      <div class="panel panel-default <%= attr %> <%= locale %>" style="display:<%= i == 0 ? 'auto' : 'none' %>;">
                        <div class="panel-heading">
                          <%= Spree.t(attr, locale: locale) %>

                          <div class="pull-right text-muted">
                            <small><i><%= Spree.t(:'i18n.this_file_language', locale: locale) %></i></small>

                            <% if locale.to_s.include?('-') %>
                                <img src="https://www.localeapp.com/assets/flags/regions/<%= locale.to_s.split('-').last %>.png">
                            <% else %>
                                <img src="https://www.localeapp.com/assets/flags/languages/<%= locale %>.png">
                            <% end %>
                          </div>
                        </div>

                        <div class="panel-body">
                          <%# cette view la est paar défaut dans spree mais c'est actually mal faite... %>
                          <% if @resource.translation.class.columns_hash[attr.to_s].type == :text %>
                              <%= g.text_area attr, class: 'form-control', rows: 4 %>
                          <% else %>
                              <%= g.text_field attr, class: 'form-control' %>
                          <% end %>
                        </div>
                      </div>
                  <% end %>

                  <div class="panel panel-default image <%= locale %>" style="display:<%= 'none'%>;">

                    <div class="panel-heading">
                      <%= Spree.t(:image, locale: locale) %>

                      <div class="pull-right text-muted">
                        <small><i><%= Spree.t(:'i18n.this_file_language', locale: locale) %></i></small>

                        <% if locale.to_s.include?('-') %>
                            <img src="https://www.localeapp.com/assets/flags/regions/<%= locale.to_s.split('-').last %>.png">
                        <% else %>
                            <img src="https://www.localeapp.com/assets/flags/languages/<%= locale %>.png">
                        <% end %>
                      </div>
                    </div>

                    <div class="panel-body">
                      <%= g.file_field :image, class: 'form-control', rows: 4 %>
                    </div>
                  </div>
              <% end %>
          <% end %>

          <p class="no-translations" style="display: none">There are no any translation for given criteria</p>
        </div>

        <hr/>
        <%= render 'spree/admin/shared/edit_resource_links' %>
    <% end %>
  </div>
</div>

app/views/spree/admin/translations/lookbook.html.erb
<% content_for :page_actions do %>
    <%= button_link_to Spree.t(:back_to_resource_list, resource: Spree::Lookbook.model_name.human), admin_lookbooks_path, class: 'btn-primary', icon: 'arrow-left' %>
<% end %>
<% @resource = @lookbook %>

<%= render 'settings' %>


<div class="row translations">
  <div class="col-md-4">
    <div class="panel panel-default fields">
      <div class="panel-heading"><%= Spree.t(:'i18n.fields') %></div>
      <div class="list-group" id="attr_list">
        <a class="list-group-item active" data-attr="name" href="#"><%= Spree.t("name") %></a>
        <a class="list-group-item" data-attr="slug" href="#"><%= Spree.t("slug") %></a>

        <a class="list-group-item " data-attr="image" href="#"><%= Spree.t("image") %></a>
        <a class="list-group-item" data-attr="meta_title" href="#"><%= Spree.t("meta_title") %></a>
        <a class="list-group-item " data-attr="meta_description" href="#"><%= Spree.t("meta_description") %></a>
      </div>
    </div>

  </div>
  <div class="col-md-8">
    <%= form_for [:admin, @lookbook], :html => {:multipart => true}  do |f| %>
        <div id="attr_fields">
          <% SpreeI18n::Config.available_locales.each do |locale| %>
              <%= f.globalize_fields_for locale.to_sym do |g| %>
                  <div class="panel panel-default name <%= locale %>" style="display:<%= 'auto'%>;">
                    <div class="panel-heading">
                      <%= Spree.t(:name, locale: locale) %>

                      <div class="pull-right text-muted">
                        <small><i><%= Spree.t(:'i18n.this_file_language', locale: locale) %></i></small>

                        <% if locale.to_s.include?('-') %>
                            <img src="https://www.localeapp.com/assets/flags/regions/<%= locale.to_s.split('-').last %>.png">
                        <% else %>
                            <img src="https://www.localeapp.com/assets/flags/languages/<%= locale %>.png">
                        <% end %>
                      </div>
                    </div>

                    <div class="panel-body">
                      <%= g.text_field :name, class: 'form-control', rows: 4 %>
                    </div>
                  </div>

                  <div class="panel panel-default slug <%= locale %>" style="display:<%= 'none'%>;">
                    <div class="panel-heading">
                      <%= Spree.t(:slug, locale: locale) %>

                      <div class="pull-right text-muted">
                        <small><i><%= Spree.t(:'i18n.this_file_language', locale: locale) %></i></small>

                        <% if locale.to_s.include?('-') %>
                            <img src="https://www.localeapp.com/assets/flags/regions/<%= locale.to_s.split('-').last %>.png">
                        <% else %>
                            <img src="https://www.localeapp.com/assets/flags/languages/<%= locale %>.png">
                        <% end %>
                      </div>
                    </div>

                    <div class="panel-body">
                      <%= g.text_field :slug, class: 'form-control', rows: 4 %>
                    </div>
                  </div>

                  <div class="panel panel-default meta_description <%= locale %>" style="display:none;">
                    <div class="panel-heading">
                      <%= Spree.t(:meta_description, locale: locale) %>

                      <div class="pull-right text-muted">
                        <small><i><%= Spree.t(:'i18n.this_file_language', locale: locale) %></i></small>

                        <% if locale.to_s.include?('-') %>
                            <img src="https://www.localeapp.com/assets/flags/regions/<%= locale.to_s.split('-').last %>.png">
                        <% else %>
                            <img src="https://www.localeapp.com/assets/flags/languages/<%= locale %>.png">
                        <% end %>
                      </div>
                    </div>

                    <div class="panel-body">
                      <%= g.text_field :meta_description, class: 'form-control', rows: 4 %>
                    </div>
                  </div>

                  <div class="panel panel-default meta_title <%= locale %>" style="display:none;">
                    <div class="panel-heading">
                      <%= Spree.t(:meta_title, locale: locale) %>

                      <div class="pull-right text-muted">
                        <small><i><%= Spree.t(:'i18n.this_file_language', locale: locale) %></i></small>

                        <% if locale.to_s.include?('-') %>
                            <img src="https://www.localeapp.com/assets/flags/regions/<%= locale.to_s.split('-').last %>.png">
                        <% else %>
                            <img src="https://www.localeapp.com/assets/flags/languages/<%= locale %>.png">
                        <% end %>
                      </div>
                    </div>

                    <div class="panel-body">
                      <%= g.text_field :meta_title, class: 'form-control', rows: 4 %>
                    </div>
                  </div>

                  <div class="panel panel-default image <%= locale %>" style="display:<%= 'none'%>;">

                    <div class="panel-heading">
                      <%= Spree.t(:image, locale: locale) %>

                      <div class="pull-right text-muted">
                        <small><i><%= Spree.t(:'i18n.this_file_language', locale: locale) %></i></small>

                        <% if locale.to_s.include?('-') %>
                            <img src="https://www.localeapp.com/assets/flags/regions/<%= locale.to_s.split('-').last %>.png">
                        <% else %>
                            <img src="https://www.localeapp.com/assets/flags/languages/<%= locale %>.png">
                        <% end %>
                      </div>
                    </div>

                    <div class="panel-body">
                      <%= g.file_field :image, class: 'form-control', rows: 4 %>
                    </div>
                  </div>



        <% end %>
          <% end %>

          <p class="no-translations" style="display: none">There are no any translation for given criteria</p>
        </div>

        <hr/>
        <%= render 'spree/admin/shared/edit_resource_links' %>
    <% end %>
  </div>
</div>